project:
  type: website
  render:
    - "*.qmd"
  output-dir: docs

from: markdown+emoji

website:
  title: ""
  page-navigation: true
  favicon: favicon.svg
  search: false
  bibliography: references.bib
  twitter-card:
    creator: "@mxochicale"
    card-style: summary
    image: favicon.svg
  open-graph:
    image: favicon.svg
  page-footer:
    right: "This page is built with {{< fa heart >}} and [Quarto](https://quarto.org/)."
    left: "&copy; 2024, Miguel Xochicale"
